dry_run: true
base_url: ""
discord:
  webhook: ""
  seeding_complete_message: "Server is live!"
  seeding_in_progress_message: "Server has reached {player_count} players"
  player_count_message: "{num_allied_players} - {num_axis_players}"
  seeding_player_buckets:
    - 10
    - 20
    - 30
poll_time_seeding: 30
poll_time_seeded: 300
requirements:
  min_allies: 0
  min_axis: 0
  max_allies: 20
  max_axis: 20
  online_when_seeded: true
  minimum_play_time:
    seconds: 0
    minutes: 5
    hours: 0
vip_reward:
  cumulative: true
  timeframe:
    minutes: 0
    hours: 0
    days: 1
    weeks: 0
  player_message: "Thank you for helping us seed.\n\nYou've been granted {vip_reward}\n\nYour VIP currently expires: {vip_expiration}"
  nice_delta: yes
  nice_date: yes
