version: "3.8"

name: hll_seed_vip
services:
    hll_seed_vip:
        environment:
            - LOGURU_LEVEL=DEBUG
            - API_KEY=${API_KEY}
        init: true
        container_name: hll_seed_vip-${COMPOSE_PROJECT_NAME}
        volumes:
            - ./logs:/code/logs
            - ./config:/code/config
        restart: unless-stopped
        image: cericmathey/hll_seed_vip:${DOCKER_TAG}
        build:
          dockerfile: ./Dockerfile
